package com.noxi.noxiapp.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // Navigation
    val navGoals: String,
    val navWorkout: String,
    val navCalendar: String,
    val navProfile: String,
    
    // Calendar
    val calendarTitle: String,
    val noWorkoutRecorded: String,
    val planned: String,
    val completed: String,
    val selectedDate: String,
    val goal: String,
    val notEntered: String,
    val note: String,
    val reps: String,
    val minutes: String,
    val set: String,
    
    // Workout
    val workoutProgram: String,
    val programs: String,
    val noSavedPrograms: String,
    val saveProgram: String,
    val programName: String,
    val save: String,
    val cancel: String,
    val ok: String,
    val day: String, // "Gün" suffix
    val editDayName: String,
    val addExercise: String,
    val exerciseName: String,
    val targetSet: String,
    val targetRep: String,
    val targetWeight: String,
    val add: String,
    
    val profile: String,
    val achievements: String,
    val settings: String,
    val themes: String,
    val habitSettings: String,
    val language: String,
    val profileName: String,
    val profileInfo: String,
    val phoneNumber: String,
    val age: String,
    val height: String,
    val weight: String,
    val saveChanges: String,
    val logout: String,
    
    // Generic
    // Generic
    val comingSoon: String,
    
    // Habits
    val today: String,
    val addHabit: String,
    val noHabitsYet: String,
    val back: String,
    val createCustomHabit: String,
    val predefinedHabits: String,
    val drinkWater: String,
    val loseWeight: String,
    val walk: String,
    val readBook: String,
    val takeVitamin: String,
    val meditate: String,
    val exercise: String,
    val daily: String,
    val pages: String,
    val pills: String,
    val pageOrMinute: String,
    val habitName: String,
    val unit: String,
    val selectColor: String,
    val selected: String,
    val icon: String,
    val selectIcon: String,
    val create: String,
    val drinkWaterSettings: String,
    val loseWeightSettings: String,
    val walkSettings: String,
    val dailyGoalGlass: String,
    val glass: String,
    val startWeightKg: String,
    val targetWeightKg: String,
    val dailyCalorieGoal: String,
    val kg: String,
    val dailyStepGoal: String,
    val steps: String,
    val incrementAmount: String,
    
    // Nutrition
    val nutritionTitle: String,
    
    // AddExerciseScreen
    val createCustomExercise: String,
    val addedExercises: String,
    val predefinedExercises: String,
    val close: String,
    val open: String,
    val delete: String,
    
    // Workout Components
    val exerciseCount: String,
    val noExercisesYet: String,
    val editName: String,
    val editDayNameTitle: String,
    val selectIconOptional: String,
    val chest: String,
    val backBody: String, // 'back' is already used for navigation back
    val shoulders: String,
    val abs: String,
    val legs: String,
    val arms: String,
    val cardio: String,
    val defaultIcon: String,
    val actualWeight: String,
    val actualReps: String,
    val actualMinutes: String,
    val addNote: String,
    
    // Calendar Additional
    val shortDays: List<String>,
    val incompleteExercises: String
)

val trStrings = AppStrings(
    navGoals = "Hedefler",
    navWorkout = "Antrenman",
    navCalendar = "Takvim",
    navProfile = "Profil",
    calendarTitle = "Takvim",
    noWorkoutRecorded = "Bu tarihte kayıtlı antrenman yok.",
    planned = "Planlandı",
    completed = "Tamamlandı",
    selectedDate = "Seçilen Tarih",
    goal = "Hedef",
    notEntered = "Henüz girilmedi",
    note = "Not",
    reps = "tekrar",
    minutes = "dakika",
    set = "set",
    workoutProgram = "Antrenman Programı",
    programs = "Programlar",
    noSavedPrograms = "Kayıtlı program yok",
    saveProgram = "Programı Kaydet",
    programName = "Program İsmi",
    save = "Kaydet",
    cancel = "İptal",
    ok = "Tamam",
    day = "Gün",
    editDayName = "Gün İsmini Düzenle",
    addExercise = "Hareket Ekle",
    exerciseName = "Hareket İsmi",
    targetSet = "Hedef Set",
    targetRep = "Hedef Tekrar",
    targetWeight = "Hedef Ağırlık (Opsiyonel)",
    add = "Ekle",
    profile = "Profil",
    achievements = "Başarımlar",
    settings = "Ayarlar",
    themes = "Temalar",
    habitSettings = "Ayarları",
    language = "Dil",
    profileName = "Ad Soyad",
    profileInfo = "Profil Bilgisi",
    phoneNumber = "Telefon Numarası",
    age = "Yaş",
    height = "Boy (cm)",
    weight = "Kilo (kg)",
    saveChanges = "Değişiklikleri Kaydet",
    logout = "Çıkış Yap",
    comingSoon = "Yakında",
    today = "Bugün",
    addHabit = "Alışkanlık Ekle",
    noHabitsYet = "Henüz alışkanlık eklemediniz\n+ butonuna tıklayarak başlayın",
    back = "Geri",
    createCustomHabit = "Özel Alışkanlık Oluştur",
    predefinedHabits = "Hazır Alışkanlıklar",
    drinkWater = "Su İç",
    loseWeight = "Kilo Ver",
    walk = "Yürüyüş Yap",
    readBook = "Kitap Oku",
    takeVitamin = "Vitamin Al",
    meditate = "Meditasyon Yap",
    exercise = "Egzersiz Yap",
    daily = "Günlük",
    pages = "sayfa",
    pills = "adet",
    pageOrMinute = "Sayfa veya Dakika",
    habitName = "Alışkanlık Adı",
    unit = "Birim",
    selectColor = "Renk Seç",
    selected = "Seçili",
    icon = "İkon",
    selectIcon = "İkon Seç",
    create = "Oluştur",
    drinkWaterSettings = "Su İç - Ayarlar",
    loseWeightSettings = "Kilo Ver - Ayarlar",
    walkSettings = "Yürüyüş Yap - Ayarlar",
    dailyGoalGlass = "Günlük Hedef (Bardak)",
    glass = "bardak",
    startWeightKg = "Başlangıç Kilosu (kg)",
    targetWeightKg = "Hedef Kilo (kg)",
    dailyCalorieGoal = "Günlük Kalori Hedefi",
    kg = "kg",
    dailyStepGoal = "Günlük Adım Hedefi",
    steps = "adım",
    incrementAmount = "Arttırma Miktarı (Örn: 1000 adım)",
    nutritionTitle = "Beslenme Sayfası",
    createCustomExercise = "Özel Hareket Oluştur",
    addedExercises = "Eklenen Hareketler",
    predefinedExercises = "Hazır Hareketler",
    close = "Kapat",
    open = "Aç",
    delete = "Sil",
    exerciseCount = "hareket",
    noExercisesYet = "Henüz hareket eklenmedi",
    editName = "İsmi Düzenle",
    editDayNameTitle = "Gün İsmini ve İkonunu Düzenle",
    selectIconOptional = "İkon Seç (Opsiyonel)",
    chest = "Göğüs",
    backBody = "Sırt",
    shoulders = "Omuz",
    abs = "Karın",
    legs = "Bacak",
    arms = "Kol",
    cardio = "Kardiyo",
    defaultIcon = "Varsayılan",
    actualWeight = "Yapılan Ağırlık (kg)",
    actualReps = "Yapılan Tekrar",
    actualMinutes = "Yapılan Dakika",
    addNote = "Not Ekle",
    shortDays = listOf("Pt", "Sa", "Ça", "Pe", "Cu", "Ct", "Pz"),
    incompleteExercises = "Tamamlanmayan Antrenman Hareketleri:"
)

val enStrings = AppStrings(
    navGoals = "Goals",
    navWorkout = "Workout",
    navCalendar = "Calendar",
    navProfile = "Profile",
    calendarTitle = "Calendar",
    noWorkoutRecorded = "No workout recorded for this date.",
    planned = "Planned",
    completed = "Completed",
    selectedDate = "Selected Date",
    goal = "Goal",
    notEntered = "Not entered yet",
    note = "Note",
    reps = "reps",
    minutes = "minutes",
    set = "sets",
    workoutProgram = "Workout Program",
    programs = "Programs",
    noSavedPrograms = "No saved programs",
    saveProgram = "Save Program",
    programName = "Program Name",
    save = "Save",
    cancel = "Cancel",
    ok = "OK",
    day = "Day",
    editDayName = "Edit Day Name",
    addExercise = "Add Exercise",
    exerciseName = "Exercise Name",
    targetSet = "Target Sets",
    targetRep = "Target Reps",
    targetWeight = "Target Weight (Optional)",
    add = "Add",
    profile = "Profile",
    achievements = "Achievements",
    settings = "Settings",
    themes = "Themes",
    habitSettings = "Settings",
    language = "Language",
    profileName = "Name Surname",
    profileInfo = "Profile Info",
    phoneNumber = "Phone Number",
    age = "Age",
    height = "Height (cm)",
    weight = "Weight (kg)",
    saveChanges = "Save Changes",
    logout = "Logout",
    comingSoon = "Coming Soon",
    today = "Today",
    addHabit = "Add Habit",
    noHabitsYet = "You haven't added any habits yet\nStart by clicking the + button",
    back = "Back",
    createCustomHabit = "Create Custom Habit",
    predefinedHabits = "Predefined Habits",
    drinkWater = "Drink Water",
    loseWeight = "Lose Weight",
    walk = "Walk",
    readBook = "Read Book",
    takeVitamin = "Take Vitamin",
    meditate = "Meditate",
    exercise = "Exercise",
    daily = "Daily",
    pages = "pages",
    pills = "pills",
    pageOrMinute = "Page or Minute",
    habitName = "Habit Name",
    unit = "Unit",
    selectColor = "Select Color",
    selected = "Selected",
    icon = "Icon",
    selectIcon = "Select Icon",
    create = "Create",
    drinkWaterSettings = "Drink Water - Settings",
    loseWeightSettings = "Lose Weight - Settings",
    walkSettings = "Walk - Settings",
    dailyGoalGlass = "Daily Goal (Glass)",
    glass = "glass",
    startWeightKg = "Start Weight (kg)",
    targetWeightKg = "Target Weight (kg)",
    dailyCalorieGoal = "Daily Calorie Goal",
    kg = "kg",
    dailyStepGoal = "Daily Step Goal",
    steps = "steps",
    incrementAmount = "Increment Amount",
    nutritionTitle = "Nutrition Page",
    createCustomExercise = "Create Custom Exercise",
    addedExercises = "Added Exercises",
    predefinedExercises = "Predefined Exercises",
    close = "Close",
    open = "Open",

    delete = "Delete",
    exerciseCount = "exercises",
    noExercisesYet = "No exercises added yet",
    editName = "Edit Name",
    editDayNameTitle = "Edit Day Name and Icon",
    selectIconOptional = "Select Icon (Optional)",
    chest = "Chest",
    backBody = "Back",
    shoulders = "Shoulders",
    abs = "Abs",
    legs = "Legs",
    arms = "Arms",
    cardio = "Cardio",
    defaultIcon = "Default",
    actualWeight = "Actual Weight (kg)",
    actualReps = "Actual Reps",
    actualMinutes = "Actual Minutes",
    
    addNote = "Add Note",
    shortDays = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
    incompleteExercises = "Incomplete Workout Exercises:"
)

val LocalStrings = staticCompositionLocalOf { trStrings }
